# Generated by Django 4.1 on 2023-07-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedad',
            options={'verbose_name': 'Propiedad', 'verbose_name_plural': 'Propiedades'},
        ),
    ]
