# Generated by Django 4.1 on 2023-07-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_alter_propiedad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='fecha',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
